import type { ComponentType } from 'react'
import type { VariantComponentProps } from '@/lib/registry/types'
import {
  HeaderV1,
  HeaderV2,
  HeaderV3,
  LogoV1,
  SearchV1,
  CartV1,
  HeroV1,
  HeroV2,
  HeroV3,
  HeroV4,
  HeroMediaV1,
  HeroOverlayV1,
  HeroTitleV1,
  HeroSubtitleV1,
  HeroButtonV1,
  HeroLogoV1,
  HeroEyebrowV1,
  HeroTitleBistroV1,
  HeroButtonBistroV1,
  HeroFeatureV1,
  ProductCardV2,
  ProductCardV4,
  ProductCardV5,
  ProductCardV6,
  ProductCardV7,
  ProductCardV9,
  ProductSectionV1,
  TemplateSectionV1,
  CategoriesV1,
  OffersV1,
  TestimonialsV1,
  OrdersV1,
  FooterV1,
  FooterV2,
} from '@/components/variants'
import {
  LoginModalSectionV1,
  LoginModalSectionV2,
  LoginModalSectionV3,
} from '@/components/variants/login-modal-sections'
import {
  CartDrawerSectionV1,
  CartDrawerSectionV2,
  CartDrawerSectionV3,
} from '@/components/variants/cart-drawer-sections'
import { AddressV1, AccountV1, DealsV1, HeaderStyleV1, StoreNameV1 } from '@/components/variants/header-parts'
import {
  NavLinkV1,
  GroceryAccountV1,
  ThemeToggleV1,
  GroceryBarStyleV1,
} from '@/components/variants/grocery-header-parts'
import {
  BistroNavLinkV1,
  MenuButtonV1,
  BistroSearchBtnV1,
  BistroAccountV1,
  BistroLogoV1,
  BistroStoreNameV1,
  BistroBarStyleV1,
  BistroCartV1,
} from '@/components/variants/bistro-header-parts'

export const variantRenderMap: Record<string, ComponentType<VariantComponentProps>> = {
  HeaderV1,
  HeaderV2,
  HeaderV3,
  LogoV1,
  SearchV1,
  CartV1,
  AddressV1,
  AccountV1,
  AccountGroceryV1: GroceryAccountV1,
  DealsV1,
  HeaderStyleV1,
  StoreNameV1,
  NavLinkV1,
  ThemeToggleV1,
  GroceryBarStyleV1,
  BistroNavLinkV1,
  MenuButtonV1,
  BistroSearchBtnV1,
  BistroAccountV1,
  BistroLogoV1,
  BistroStoreNameV1,
  BistroBarStyleV1,
  BistroCartV1,
  HeroV1,
  HeroV2,
  HeroV3,
  HeroV4,
  HeroMediaV1,
  HeroOverlayV1,
  HeroTitleV1,
  HeroTitleBistroV1,
  HeroSubtitleV1,
  HeroButtonV1,
  HeroButtonBistroV1,
  HeroLogoV1,
  HeroEyebrowV1,
  HeroFeatureV1,
  ProductCardV1: ProductCardV4,
  ProductCardV2,
  ProductCardV3: ProductCardV4,
  ProductCardV4,
  ProductCardV5,
  ProductCardV6,
  ProductCardV7,
  ProductCardV8: ProductCardV4,
  ProductCardV9,
  ProductSectionV1,
  TemplateSectionV1,
  CategoriesV1,
  OffersV1,
  TestimonialsV1,
  OrdersV1,
  FooterV1,
  FooterV2,
  LoginModalV1: LoginModalSectionV1,
  LoginModalV2: LoginModalSectionV2,
  LoginModalV3: LoginModalSectionV3,
  CartDrawerV1: CartDrawerSectionV1,
  CartDrawerV2: CartDrawerSectionV2,
  CartDrawerV3: CartDrawerSectionV3,
}

export function getVariantComponent(variantId: string): ComponentType<VariantComponentProps> | null {
  return variantRenderMap[variantId] ?? null
}
