/** Iconify icon names per component / section type */
export const NODE_TYPE_ICONS: Record<string, string> = {
  header: 'solar:widget-5-bold-duotone',
  footer: 'solar:align-bottom-bold-duotone',
  hero: 'solar:gallery-wide-bold-duotone',
  heroMedia: 'solar:gallery-bold-duotone',
  heroOverlay: 'solar:mask-happly-bold-duotone',
  heroTitle: 'solar:text-bold-duotone',
  heroSubtitle: 'solar:text-field-bold-duotone',
  heroButton: 'solar:round-arrow-right-bold-duotone',
  heroLogo: 'solar:star-bold-duotone',
  heroEyebrow: 'solar:text-circle-bold-duotone',
  heroFeature: 'solar:widget-5-bold-duotone',
  categories: 'solar:widget-4-bold-duotone',
  offers: 'solar:sale-bold-duotone',
  productSection: 'solar:bag-4-bold-duotone',
  templateSection: 'solar:layers-minimalistic-bold-duotone',
  productCard: 'solar:box-bold-duotone',
  testimonials: 'solar:chat-round-like-bold-duotone',
  orders: 'solar:clipboard-list-bold-duotone',
  loginModal: 'solar:login-3-bold-duotone',
  cartDrawer: 'solar:cart-large-2-bold-duotone',
  cartDrawerHeader: 'solar:text-bold-duotone',
  cartStepNav: 'solar:route-bold-duotone',
  cartLineItem: 'solar:bag-3-bold-duotone',
  cartBill: 'solar:bill-list-bold-duotone',
  cartCta: 'solar:round-arrow-right-bold-duotone',
  cartCoupon: 'solar:ticket-sale-bold-duotone',
  cartDrawerStyle: 'solar:palette-bold-duotone',
  logo: 'solar:star-bold-duotone',
  storeName: 'solar:shop-bold-duotone',
  address: 'solar:map-point-bold-duotone',
  search: 'solar:magnifer-bold-duotone',
  deals: 'solar:sale-bold-duotone',
  account: 'solar:user-circle-bold-duotone',
  cart: 'solar:cart-large-2-bold-duotone',
  headerStyle: 'solar:palette-bold-duotone',
  navLink: 'solar:link-round-bold-duotone',
  themeToggle: 'solar:sun-2-bold-duotone',
  groceryBarStyle: 'solar:paint-roller-bold-duotone',
  menuButton: 'solar:hamburger-menu-bold-duotone',
  bistroBarStyle: 'solar:palette-bold-duotone',
}

export function getNodeTypeIcon(type: string): string {
  return NODE_TYPE_ICONS[type] ?? 'solar:layers-bold-duotone'
}

export const SECTION_ADD_ICONS: Record<string, string> = {
  header: 'solar:widget-5-bold-duotone',
  footer: 'solar:align-bottom-bold-duotone',
  hero: 'solar:gallery-wide-bold-duotone',
  categories: 'solar:widget-4-bold-duotone',
  offers: 'solar:sale-bold-duotone',
  productSection: 'solar:bag-4-bold-duotone',
  testimonials: 'solar:chat-round-like-bold-duotone',
  orders: 'solar:clipboard-list-bold-duotone',
  loginModal: 'solar:login-3-bold-duotone',
  cartDrawer: 'solar:cart-large-2-bold-duotone',
}
